### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by PocketNinjaDesign** [PocketNinjaDesign/Yo#8]
This could be a tricky one :-S

**Comment by eyeamaman** [comment]
Maybe it could be that you just don't allow for it as it could be bad practice..?

**Comment by eyeamaman** [comment]
So I'm thinking, adding a script to check if another script it's dependent on also depends on the main script.  So storing the list of dependencies in the Loaded state.

**Comment by eyeamaman** [comment]
Code has been re-written to prepare for this.  A main issue where scripts could be activated before all dependencies were loaded was sorted.

Still need to add a check for hidden circular dependencies.

**Comment by PocketNinjaCoUk** [comment]
This could be doable by adding a dependency chain array through each script

**Comment by PocketNinjaDesign** [comment]
People just shouldn't be so stupid :-D !!!!
